module.exports = [
	'Caught (poach/hunt/trade)',
	'Caught/picked up by people',
	'Caught/trapped (conflict)',
	'Disease/Debility',
	'Fallen into pit/trench/well',
	'Flood/river induced',
	'Impact (glass,wire,vehicle)',
	'Injury (electrocution)',
	'Injury (people/dog/cat)',
	'Injury (predation)',
	'Injury (road/train hit)',
	'Injury (unknown)',
	'Left behind (conflict)',
	'Moved into human habitats',
	'Nest/Tree/Chick fall',
	'Orphan (parent killed)',
	'Stranded population',
	'Unknown (confiscated)',
	'Unknown (found alone)',
	'Others',
];
